server:
  port: 8081

spring:
  data:
    mongodb:
      host: 192.168.5.6
      port: 50000
      database: cloudwork
      username: xh_rw
      password: XHTec@2016
      authentication-database: admin